feat: add forecast method
cmu-delphi/epipredict pull request #319
Opened 2024-04-12 22:46 UTC by dshemetov

### Checklist

Please:

- [x] Make sure this PR is against "dev", not "main".
- [x] Request a review from one of the current epipredict main reviewers:
      dajmcdon.
- [x] Make sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
      Always increment the patch version number (the third number), unless you are
      making a release PR from dev to main, in which case increment the minor
      version number (the second number).
- [x] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      0.7.2, then write your changes under the 0.8 heading).
- [x] Consider pinning the `epiprocess` version in the `DESCRIPTION` file if
  - You anticipate breaking changes in `epiprocess` soon
  - You want to co-develop features in `epipredict` and `epiprocess`

### Change explanations for reviewer

A very simple PoC we discussed adding the forecast function. Not sure if I stored the `train_data` in the right place, currently in `epi_workflow$fit$meta$train_data`, hopefully won't clobber anything there. Might be able to use `...` instead of duplicating `get_train_data` args (though might be moot if we're aiming to deprecate that function anyway).

TODO:
- [ ] more tests, with other forecasters
- [ ] replace uses of `predict` in vignettes and examples with `forecast`

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #293

2024-04-13 15:23 UTC, dajmcdon commented on R/epi_workflow.R
> +    train_data = data
I think I would just store it in a new slot: `object$original_data`.

2024-04-13 15:23 UTC, dajmcdon commented on R/epi_workflow.R
> +    cli_abort("The epi_workflow is not trained.")
Best to use the [cli formatting](https://cli.r-lib.org/articles/semantic-cli.html#inline-lists-of-items)

2024-04-15 18:15 UTC, dajmcdon commented on R/epi_workflow.R
> +  }
```suggestion
    cli_abort(c(
      "Calling `forecast()` on a {.cls workflow} that has not been trained.",
      i = "Please use `fit()` before forecasting."
      ))
  }
```

2024-04-16 15:25 UTC, dajmcdon requested changes
* Major change: `forecast` needs to be a method, not a standalone.
* Minor issue: we should perhaps think about how many of the tests should be pivoted. I'm not sure it's a bad idea to duplicate or keep some as is to ensure that both options continues to work going forward.

2024-04-24 21:25 UTC, dshemetov commented on R/flatline_forecaster.R
> +  )) %>%
I don't know, I get warnings when I remove suppressWarnings in flatline_forecaster [here](https://github.com/cmu-delphi/epipredict/blob/8a516e96bbd0d647291700c32da9d4c5182e9f13/R/flatline_forecaster.R#L72) and that makes the tests [here](https://github.com/cmu-delphi/epipredict/blob/8a516e96bbd0d647291700c32da9d4c5182e9f13/tests/testthat/test-layer_residual_quantiles.R#L84-L89) fail. The warning is:

```
Detected an unexpected many-to-many relationship between `x` and `y`.
i Row 1 of `x` matches multiple rows in `y`.
i Row 1 of `y` matches multiple rows in `x`.
i If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
```

The warnings might be different for different forecasters. Fixing these seems out of scope for this PR.

2024-04-24 21:37 UTC, dshemetov commented
FWIW, there are still many tests that I did not pivot over and those were the ones that used a non-standard new_data setting. I also have a test to compare the output of a `forecast()` call with an equivalent `predict()` call. So I don't feel like `predict()` is losing much in test coverage.

2024-04-24 21:43 UTC, dshemetov commented on R/layer_cdc_flatline_quantiles.R
> +#' preds <- suppressWarnings(forecast(wf)) %>%
No, I think I can remove this one

2024-04-24 21:45 UTC, dshemetov commented on tests/testthat/test-population_scaling.R
> +  suppressWarnings(p <- forecast(wf))
No, looks like I can remove these

2024-04-24 21:45 UTC, dshemetov commented on vignettes/epipredict.Rmd
> +This call produces a warning, which we'll ignore for now. But essentially, it's telling us that our data comes from May 2022 but we're trying to do a forecast for January 2022. The result is likely n
Done, see #322

2024-04-24 21:48 UTC, dshemetov commented on R/flatline_forecaster.R
> +  )) %>%
Undoing `suppressWarnings` in `cdc_baseline_forecaster` gives
```
Using an external vector in selections was deprecated in tidyselect 1.1.0.
i Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(col_names)

  # Now:
  data %>% select(all_of(col_names))

Backtrace:
     ▆
  1. ├─epipredict::cdc_baseline_forecaster(...) at test-snapshots.R:39:3
  2. │ ├─... %>% ... at epipredict/R/cdc_baseline_forecaster.R:105:3
  3. │ ├─stats::predict(wf, new_data = latest)
  4. │ └─epipredict:::predict.epi_workflow(wf, new_data = latest)
  5. │   ├─epipredict::apply_frosting(object, components, new_data, ...) at epipredict/R/epi_workflow.R:272:3
  6. │   └─epipredict:::apply_frosting.epi_workflow(...) at epipredict/R/frosting.R:337:3
  7. │     ├─epipredict::slather(la, components, workflow, new_data) at epipredict/R/frosting.R:403:7
  8. │     └─epipredict:::slather.layer_unnest(la, components, workflow, new_data) at epipredict/R/layers.R:206:3
  9. │       └─components$predictions %>% tidyr::unnest(col_names) at epipredict/R/layer_unnest.R:34:5
 10. ├─dplyr::mutate(., target_date = forecast_date + ahead * args_list$data_frequency)
 11. ├─dplyr::select(., -time_value)
 12. ├─tibble::as_tibble(.)
 13. ├─tidyr::unnest(., col_names)
 14. ├─epiprocess:::unnest.epi_df(., col_names)
 15. │ └─dplyr::dplyr_reconstruct(NextMethod(), data) at cmu-delphi-epiprocess-00c0a85/R/methods-epi_df.R:239:3
 16. │   └─dplyr:::dplyr_new_data_frame(data)
 17. │     ├─row.names %||% .row_names_info(x, type = 0L)
 18. │     └─base::.row_names_info(x, type = 0L)
 19. ├─base::NextMethod() at cmu-delphi-epiprocess-00c0a85/R/methods-epi_df.R:239:3
 20. └─tidyr:::unnest.data.frame(., col_names)
 21.   └─tidyselect::eval_select(expr = enquo(cols), data = data, allow_rename = FALSE)
 22.     └─tidyselect:::eval_select_impl(...)
 23.       ├─tidyselect:::with_subscript_errors(...)
 24.       │ └─base::withCallingHandlers(...)
 25.       └─tidyselect:::vars_select_eval(...)
 26.         └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 27.           └─tidyselect:::eval_sym(expr, data_mask, context_mask)
```

2024-04-24 21:52 UTC, dshemetov commented on R/flatline_forecaster.R
> +  )) %>%
I removed a bunch of other suppressWarnings in the tests and things were fine.

Removing [this one](https://github.com/cmu-delphi/epipredict/blob/8a516e96bbd0d647291700c32da9d4c5182e9f13/R/dist_quantiles.R#L33) gave no warnings or errors in tests, but I'm not sure what this was intended to suppress, so I'm not comfortable removing that.

2024-04-24 22:49 UTC, dajmcdon commented
On the warnings, it used to be that running a forecaster would _always_ warn (because the data had as_of sometime in the past). I removed that warning. But all these others should be fixed. Agreed out of scope, but now that you've identified the problematic ones, can you create an issue for them?

2024-04-25 00:20 UTC, dshemetov commented
Made #323 to track those

2024-04-26 17:04 UTC, dajmcdon approved these changes
Just a small suggestion for the method itself. Hopefully, you can just accept (assuming you agree) and CI will still pass.

2024-04-30 23:13 UTC, merged

2024-05-02 23:46 UTC, dshemetov commented
In my notes from our last sync, we planned 3 PRs related to the discussions in that issue:
- Add a forecast() function (this PR)
- Rewrite the get_test_data() function (tbd)
- Change predict to “join new data onto old and forecast” (tbd)

I'm happy to tackle the latter two in the coming months, though we'll probably need to sync and clarify how we're going to tackle those.